import { test, expect, prompts, nonMeaningfulPromptCases } from '../fixtures/test-fixtures';

/**
 * Main test runner for the Newsela assignment creation workflow.
 * Scenario IDs reference TEST_PLAN.md.
 *
 * Step 3 note: the student prompt is AI-generated by "Luna" — assertions on
 * that content are PROPERTY-BASED (present, editable, persistent, changed
 * after regenerate), never exact-text. See TEST_PLAN.md §4.1.
 */

test.describe('Assignment creation workflow', () => {
  test('TC-01 [Critical] teacher creates an assignment end-to-end and receives a shareable link', async ({
    loggedIn,
    assignmentsPage,
    createModal,
    confirmationModal,
  }) => {
    await assignmentsPage.openCreateAssignmentModal();
    await createModal.expectOpen();

    await createModal.completeStep1();
    await createModal.completeStep2();
    // Step 3: verify Luna pre-filled the prompt, apply a small teacher edit
    // (human-in-the-loop, as the product's own disclaimer requests), advance.
    await createModal.completeStep3(' Support your answer with evidence from the text.');
    await createModal.completeStep4();
    await createModal.completeStep5AndSave();

    await confirmationModal.expectReady();
    const link = await confirmationModal.captureAndPrintAssignmentLink();
    expect(link).toContain('newsela');
  });
});

test.describe('Step 3 — AI-generated student prompt (Luna)', () => {
  // Each test navigates to Step 3 fresh; kept explicit (not a fixture) so the
  // journey is visible in the test body per POM-readability goals.
  async function goToStep3({ assignmentsPage, createModal }: any) {
    await assignmentsPage.openCreateAssignmentModal();
    await createModal.completeStep1();
    await createModal.completeStep2();
  }

  test('S3-01 [Critical] Luna pre-fills a non-empty prompt on arrival, with the review disclaimer visible', async ({
    loggedIn, assignmentsPage, createModal,
  }) => {
    await goToStep3({ assignmentsPage, createModal });

    await createModal.expectPromptPrefilled();
    await createModal.expectDisclaimerVisible(); // S3-10: guardrail as requirement
  });

  test('S3-02 [High] clearing the prompt blocks progression — no empty prompts reach students', async ({
    loggedIn, assignmentsPage, createModal,
  }) => {
    await goToStep3({ assignmentsPage, createModal });

    await createModal.expectPromptPrefilled();
    await createModal.clearPrompt();
    await createModal.expectCannotAdvance();
  });

  test('S3-03 [High] teacher edits persist across Next/Back — edited version wins over AI original', async ({
    loggedIn, assignmentsPage, createModal,
  }) => {
    const teacherEdit = 'TEACHER-EDIT-MARKER: cite two details from the text.';
    await goToStep3({ assignmentsPage, createModal });

    await createModal.expectPromptPrefilled();
    await createModal.appendToPrompt(` ${teacherEdit}`);
    await createModal.clickNext();
    await createModal.clickBack();

    await createModal.expectPromptText(teacherEdit);
  });

  test('S3-07 [High] regenerate produces new non-empty content and the editor survives the async cycle', async ({
    loggedIn, assignmentsPage, createModal,
  }) => {
    await goToStep3({ assignmentsPage, createModal });
    await createModal.expectPromptPrefilled();

    const { before, after } = await createModal.regeneratePrompt();
    expect(after.trim()).not.toBe(before.trim());

    // Editor must remain functional after regeneration:
    await createModal.appendToPrompt(' Post-regenerate edit works.');
    await createModal.expectPromptText('Post-regenerate edit works.');
  });

  test('S3-06 [Critical] script payload typed into the editor is inert (stored XSS — content is student-facing)', async ({
    loggedIn, assignmentsPage, createModal, page,
  }) => {
    page.on('dialog', () => {
      throw new Error('XSS payload executed: an alert dialog was triggered');
    });

    await goToStep3({ assignmentsPage, createModal });
    await createModal.expectPromptPrefilled();

    await createModal.replacePrompt(prompts.xssPayload);
    await createModal.clickNext();
    await createModal.clickBack();

    // Round-trips as literal text, does not execute:
    await createModal.expectPromptText('Explain the article');
  });

  test('S3-06b [Medium] unicode content (accents, CJK, emoji) round-trips intact', async ({
    loggedIn, assignmentsPage, createModal,
  }) => {
    await goToStep3({ assignmentsPage, createModal });
    await createModal.expectPromptPrefilled();

    await createModal.replacePrompt(prompts.unicode);
    await createModal.clickNext();
    await createModal.clickBack();

    await createModal.expectPromptText('¿Cómo cambió el personaje?');
  });

  // Data-driven: one test per input case (fixtures/test-fixtures.ts), so a
  // failure on one case doesn't take the others' observations down with it.
  for (const { label, value } of nonMeaningfulPromptCases) {
    test(`S3-11 [Medium] non-meaningful prompt (${label}) — input is never silently discarded`, async ({
      loggedIn, assignmentsPage, createModal,
    }) => {
      await goToStep3({ assignmentsPage, createModal });
      await createModal.expectPromptPrefilled();
      await createModal.replacePrompt(value);

      const outcome = await createModal.tryAdvanceAndReport();
      console.log(`\nS3-11 (${label}) observed behavior: ${outcome}\n`);

      // Deliberately NOT asserting accept-vs-block: intended product behavior
      // is unconfirmed (TEST_PLAN.md §4.3). What IS asserted, on either
      // branch: the app never silently discards the teacher's input.
      if (outcome === 'blocked') {
        await createModal.expectPromptText(value);
      } else {
        // Advanced to Step 4 — confirm the value that arrived there is the
        // one the teacher typed, not something silently substituted/emptied
        // (same Back-and-check approach as S3-03).
        await createModal.clickBack();
        await createModal.expectPromptText(value);
      }
    });
  }
});

  test('TC-06 [Medium] invalid password shows an error and does not authenticate', async ({
    loginPage,
  }) => {
    // No fallback: an unset variable must fail loudly, not silently turn this
    // into an invalid-USERNAME test (the app returns the same error for both).
    const username = process.env.NEWSELA_USERNAME;
    if (!username) {
      throw new Error('Missing NEWSELA_USERNAME — copy .env.example to .env');
    }

    await loginPage.goto();
    await loginPage.login(username, 'deliberately-wrong-password');
    await loginPage.expectLoginError();
    await loginPage.expectNotAuthenticated();
  });
